Davidmandic/project/js string 2
Pannonians/learning-js pull request #16
Opened 2022-07-26 08:55 UTC by PannoniansDavid

Solving index.js conflict issue!

2022-07-27 08:07 UTC, pvukmanovic-pannonians requested changes

2022-07-27 08:07 UTC, pvukmanovic-pannonians commented on nano.save
> +
Ne treba ti ovaj fajl. Mozes obrisati. ^_^

2022-07-28 11:37 UTC, pvukmanovic-pannonians commented
Ovde i dalje imamo konflikt ^_^

2022-07-28 12:45 UTC, closed without merging

2022-07-28 12:46 UTC, PannoniansDavid commented
This is not needed anymore (the old one) since it will change index.js page. 
I don't want to overwrite changes.