Nikolina/media hunt project
Pannonians/learning-js pull request #67
Opened 2022-08-22 11:58 UTC by Ninolina88

Done Us #55 and #56

2022-08-22 14:20 UTC, pvukmanovic-pannonians requested changes

2022-08-22 14:20 UTC, pvukmanovic-pannonians commented on Public/media-hunt/package-lock.json
> +{
Molim te obriši package-lock. Koristite yarn.

2022-08-22 14:36 UTC, pvukmanovic-pannonians commented
Please remove this content from index.js. that content will come near the end of the project.

2022-08-23 07:28 UTC, Ninolina88 commented on nikolina/package.json
> -}
igrala sam se kako ne treba na gitu. Reseno.

2022-08-23 07:28 UTC, Ninolina88 commented on Public/media-hunt/package-lock.json
> +{
Obrisano.

2022-08-23 07:30 UTC, Ninolina88 commented
Content from index.js removed as per request.

2022-08-23 08:02 UTC, pvukmanovic-pannonians submitted a review, later dismissed

2022-08-23 08:07 UTC, pvukmanovic-pannonians requested changes
Please add to the root `package.json` file workspace so that media-hunt's scripts can be executed.

2022-08-23 08:07 UTC, pvukmanovic-pannonians commented on nikolina/package.json
> +  ]
Please revert these changes. Please don't make any changes to files outside of the scope, and the scope was to scaffold project.

2022-08-23 09:29 UTC, pvukmanovic-pannonians reviewed
Let's finalize root package json

2022-08-23 09:29 UTC, pvukmanovic-pannonians commented on package.json
>    "scripts": {
Please also add the script so you could execute commands. Like `yarn nikolina appname`, but for this to be something like `yarn public moviehunt`

2022-08-23 09:30 UTC, pvukmanovic-pannonians requested changes
Missing bits for package json

2022-08-23 10:42 UTC, pvukmanovic-pannonians approved these changes
LGTM (looks good to me)

2022-08-23 10:58 UTC, merged