#59 logic for fetching single resources created
Pannonians/learning-js pull request #73
Opened 2022-09-15 10:59 UTC by Ninolina88

logic for fetching single resources created
NOTE: David is working on commands (commands folder) on a different branch.

2022-09-15 12:35 UTC, pvukmanovic-pannonians requested changes

2022-09-15 12:35 UTC, pvukmanovic-pannonians commented on public/media-hunt/http/tv.js
> +    });
Either use await or then

2022-09-15 12:37 UTC, pvukmanovic-pannonians requested changes
Please also use returns, don't just console log

2022-09-16 12:23 UTC, Ninolina88 commented on public/media-hunt/http/tv.js
> +    });
done

2022-09-19 12:50 UTC, pvukmanovic-pannonians approved these changes

2022-09-19 13:00 UTC, merged